# Generated by Django 4.1.5 on 2023-01-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nodes_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_location', models.CharField(blank=True, max_length=30, null=True)),
                ('humidity', models.CharField(blank=True, max_length=30, null=True)),
                ('CO2', models.CharField(blank=True, max_length=30, null=True)),
                ('CO2_low', models.CharField(blank=True, max_length=30, null=True)),
                ('CO2_high', models.CharField(blank=True, max_length=30, null=True)),
                ('tempreture', models.CharField(blank=True, max_length=30, null=True)),
                ('tempreture_low', models.CharField(blank=True, max_length=30, null=True)),
                ('tempreture_high', models.CharField(blank=True, max_length=30, null=True)),
                ('humidity_high', models.CharField(blank=True, max_length=30, null=True)),
                ('humidity_low', models.CharField(blank=True, max_length=30, null=True)),
                ('battery', models.CharField(blank=True, max_length=30, null=True)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('delete_status', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('uuid', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('date_time', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
