# Generated by Django 4.1.5 on 2023-01-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='date_time',
        ),
    ]
