# Generated by Django 4.1.5 on 2023-01-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_remove_nodes_model_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(blank=True, max_length=30, null=True)),
                ('temperature', models.CharField(blank=True, max_length=30, null=True)),
                ('CO2', models.CharField(blank=True, max_length=30, null=True)),
                ('uuid', models.CharField(blank=True, max_length=30, null=True)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('battery', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
