# Generated by Django 4.1.5 on 2023-01-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_post_nodes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_nodes',
            old_name='temperature',
            new_name='tempreture',
        ),
    ]
