# Generated by Django 4.1.5 on 2023-01-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_rename_temperature_post_nodes_tempreture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
