# Generated by Django 4.1.5 on 2023-01-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_alter_nodes_model_date_alter_nodes_model_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
