# Generated by Django 4.1.5 on 2023-01-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_nodes_model_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
