# Generated by Django 4.1.5 on 2023-01-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_alter_nodes_model_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_nodes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='updated_at',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
