# Generated by Django 4.1.5 on 2023-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_post_nodes_updated_at_alter_nodes_model_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_nodes',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
