# Generated by Django 4.1.5 on 2023-01-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_post_nodes_date_post_nodes_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_nodes',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
