# Generated by Django 4.1.5 on 2023-01-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_alter_post_nodes_date_alter_post_nodes_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
