# Generated by Django 4.1.5 on 2023-01-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0012_alter_nodes_model_co2_alter_nodes_model_co2_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='delete_status',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
