# Generated by Django 4.1.5 on 2023-01-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0014_alter_nodes_model_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='CO2',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='battery',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='humidity',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='tempreture',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
