# Generated by Django 4.1.5 on 2023-01-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0016_nodes_model_delete_status_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='delete_status_2',
            field=models.CharField(blank=True, choices=[('Deleted', 'Deleted'), ('Restore', 'Restore')], default='Restore', max_length=300, null=True, verbose_name='Delete Status'),
        ),
    ]
