# Generated by Django 4.1.5 on 2023-01-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0022_alter_nodes_model_co2_high_alter_nodes_model_co2_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='CO2',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='CO2_high',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='CO2_low',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='battery',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='humidity',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='humidity_high',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='humidity_low',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='tempreture',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='tempreture_high',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='tempreture_low',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='updated_at',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
