# Generated by Django 4.1.5 on 2023-03-04 18:32

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0023_alter_nodes_model_co2_alter_nodes_model_co2_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='sensitive_data',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=300, null=True)),
        ),
    ]
