# Generated by Django 4.1.5 on 2023-03-04 19:01

from django.db import migrations
import encrypted_fields.fields
import node.models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0024_nodes_model_sensitive_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='_sensitive_data',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='sensitive_data', hash_key=node.models.get_hash_key, max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='sensitive_data',
            field=encrypted_fields.fields.EncryptedIntegerField(blank=True, help_text='Your favorite number.', null=True),
        ),
    ]
