# Generated by Django 4.1.5 on 2023-03-04 19:14

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0026_alter_nodes_model_sensitive_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='_sensitive_data',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='sensitive_data', hash_key='8222a7fd4b33e333fd5cfcd2b2c03473515a397855ded9b674bb2779110d8736', max_length=66, null=True),
        ),
    ]
