# Generated by Django 4.1.5 on 2023-03-11 16:08

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0027_alter_nodes_model__sensitive_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='sensitive_data',
            field=encrypted_fields.fields.EncryptedIntegerField(blank=True, help_text='Your favorite number.', null=True),
        ),
    ]
