# Generated by Django 4.1.5 on 2023-03-11 16:12

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0028_alter_nodes_model_sensitive_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='sensitive_data',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
