# Generated by Django 4.1.5 on 2023-03-11 16:26

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0029_alter_nodes_model_sensitive_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='_sensitive_data',
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='CO2',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='CO2_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='CO2_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='battery',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='date',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='delete_status',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='delete_status_2',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, choices=[('Restore', 'Restore')], default='Restore', max_length=300, null=True, verbose_name='Delete Status'),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='email',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='humidity',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='humidity_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='humidity_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='location',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='machine',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='sub_location',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='tempreture',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='tempreture_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='tempreture_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='time',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='updated_at',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='user_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='uuid',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
