# Generated by Django 4.1.5 on 2023-03-11 16:40

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0031_nodes_model__delete_status_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='_user_name',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='user_name', hash_key='8222a7fd4b33e333fd5cfcd2b2c03473515a397855ded9b674bb2779110d8736', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='_uuid',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='uuid', hash_key='8222a7fd4b33e333fd5cfcd2b2c03473515a397855ded9b674bb2779110d8736', max_length=66, null=True),
        ),
    ]
