# Generated by Django 4.1.5 on 2023-03-18 12:54

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0032_nodes_model__user_name_nodes_model__uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_nodes',
            name='CO2',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='battery',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='date',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='humidity',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='tempreture',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='time',
            field=encrypted_fields.fields.EncryptedDateTimeField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='updated_at',
            field=encrypted_fields.fields.EncryptedDateTimeField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='user_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='uuid',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
