# Generated by Django 4.1.5 on 2023-03-18 13:10

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0034_post_nodes__date_post_nodes__time_post_nodes__uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='_delete_status_2',
        ),
        migrations.RemoveField(
            model_name='nodes_model',
            name='delete_status_2',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='_date',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='_time',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='_uuid',
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='_delete_status',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='delete_status', hash_key='8222a7fd4b33e333fd5cfcd2b2c03473515a397855ded9b674bb2779110d8736', max_length=66, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='delete_status',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='Not Deleted', editable=False, max_length=300, null=True),
        ),
    ]
