# Generated by Django 4.1.5 on 2023-03-21 09:09

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0035_remove_nodes_model__delete_status_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes_model',
            name='delete_status',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='Restore', editable=False, max_length=300, null=True),
        ),
    ]
