# Generated by Django 4.1.5 on 2023-03-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0036_alter_nodes_model_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_nodes',
            name='CO2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='battery',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='humidity',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='tempreture',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='updated_at',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='user_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='uuid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
