# Generated by Django 4.1.5 on 2023-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0037_alter_post_nodes_co2_alter_post_nodes_battery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_nodes',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post_nodes',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
