# Generated by Django 4.1.5 on 2023-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0038_alter_post_nodes_date_alter_post_nodes_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='sensitive_data',
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='faulty',
            field=models.CharField(blank=True, default='False', max_length=300, null=True),
        ),
    ]
