# Generated by Django 4.1.5 on 2023-03-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0039_remove_nodes_model_sensitive_data_post_nodes_faulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='updated_at',
        ),
    ]
