# Generated by Django 4.1.5 on 2023-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0040_remove_nodes_model_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=300, null=True)),
                ('theme', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
