# Generated by Django 4.1.5 on 2023-04-04 07:43

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0041_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='latitude',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='longitude',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
