# Generated by Django 4.1.5 on 2023-04-11 16:05

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0042_nodes_model_latitude_nodes_model_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodes_model',
            old_name='CO2',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='nodes_model',
            old_name='CO2_high',
            new_name='current_high',
        ),
        migrations.RenameField(
            model_name='nodes_model',
            old_name='CO2_low',
            new_name='current_low',
        ),
        migrations.RenameField(
            model_name='nodes_model',
            old_name='humidity_high',
            new_name='lpm',
        ),
        migrations.RenameField(
            model_name='nodes_model',
            old_name='humidity',
            new_name='power',
        ),
        migrations.RenameField(
            model_name='nodes_model',
            old_name='humidity_low',
            new_name='power_high',
        ),
        migrations.RenameField(
            model_name='nodes_model',
            old_name='tempreture_high',
            new_name='power_low',
        ),
        migrations.RenameField(
            model_name='nodes_model',
            old_name='tempreture',
            new_name='voltage',
        ),
        migrations.RenameField(
            model_name='nodes_model',
            old_name='tempreture_low',
            new_name='voltage_high',
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='voltage_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
