# Generated by Django 4.1.5 on 2023-04-11 16:07

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0043_rename_co2_nodes_model_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='lpm_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='lpm_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='nodes_model',
            name='lpm',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
