# Generated by Django 4.1.5 on 2023-04-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0044_nodes_model_lpm_high_nodes_model_lpm_low_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_nodes',
            old_name='CO2',
            new_name='current',
        ),
        migrations.RenameField(
            model_name='post_nodes',
            old_name='humidity',
            new_name='power',
        ),
        migrations.RenameField(
            model_name='post_nodes',
            old_name='tempreture',
            new_name='voltage',
        ),
    ]
