# Generated by Django 4.1.5 on 2023-04-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0045_rename_co2_post_nodes_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_nodes',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='current',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='faulty',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='power',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='time',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='post_nodes',
            name='voltage',
        ),
    ]
