# Generated by Django 4.1.5 on 2023-04-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0046_remove_post_nodes_battery_remove_post_nodes_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_nodes',
            name='battery',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='current',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='faulty',
            field=models.CharField(blank=True, default='False', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='power',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='user_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='uuid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='voltage',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
