# Generated by Django 4.1.5 on 2023-04-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0047_post_nodes_battery_post_nodes_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_nodes',
            name='lpm',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
