# Generated by Django 4.1.5 on 2023-05-02 14:28

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0048_post_nodes_lpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes_model',
            name='energy',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='energy_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='energy_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='frequency',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='frequency_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='frequency_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='power_factor',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='power_factor_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='power_factor_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='shaft_speed',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='shaft_speed_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='shaft_speed_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='torque',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='torque_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='torque_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='windspeed',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='windspeed_high',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='nodes_model',
            name='windspeed_low',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=300, null=True),
        ),
    ]
