# Generated by Django 4.1.5 on 2023-05-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0049_nodes_model_energy_nodes_model_energy_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes_model',
            name='lpm',
        ),
        migrations.RemoveField(
            model_name='nodes_model',
            name='lpm_high',
        ),
        migrations.RemoveField(
            model_name='nodes_model',
            name='lpm_low',
        ),
    ]
