# Generated by Django 4.1.5 on 2023-05-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0050_remove_nodes_model_lpm_remove_nodes_model_lpm_high_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_nodes',
            name='lpm',
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='energy',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='frequency',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='power_factor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='shaft_speed',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='torque',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post_nodes',
            name='windspeed',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
